summary: A command-line tool to help you insert the correct compiler options when compiling objects and/or linking libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2 
bin-url: https://github.com/leleliu008/uppm-package-repository-openbsd-7.4-amd64/releases/download/2025.07.25/pkg-config-0.29.2-openbsd-7.4-amd64.release.tar.xz 
bin-sha: 4fc1b0eb749f3ec9f1f0d32e46d773ec5f8a72afc184f8f9a54004bd54420625
