summary: Manage compile and link flags for libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/leleliu008/uppm-package-repository-openbsd-7.4-amd64/releases/download/2023.12.08/pkg-config-0.29.2-openbsd-7.4-amd64.tar.xz
bin-sha: 57324a5d01233546b5b063ff07d164b5b49c48ab36cb0d9c0094a8f263011699
